# Generated by Django 5.2.5 on 2025-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='order',
        ),
    ]
