# Generated by Django 5.2.5 on 2025-08-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('rent_per_day', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
